namespace: cpl-coverage

git:
  repoURL: https://github.com/maladroitcat/geospatial-analysis.git
  ref: geospatial_analysis

s3:
  bucketName: cpl-data
  bucketClass: openshift-storage.noobaa.io

seed:
  enabled: true

pipeline:
  image: image-registry.openshift-image-registry.svc:5000/cpl-coverage/cpl-pipeline:latest

secrets:
  mapboxToken: ""
  censusApiKey: ""
