namespace: cpl-coverage

git:
  repoURL: https://github.com/maladroitcat/geospatial-analysis.git
  ref: geospatial_analysis

s3:
  bucketName: cpl-coverage-data
  bucketClass: openshift-storage.noobaa.io

seed:
  enabled: true

secrets:
  mapboxToken: "pk.eyJ1IjoiYWJieXJleW5vbGRzODgiLCJhIjoiY2xqZXBiZzB6MjlzZjNlc2NqNm5ycnZuaSJ9.WrtemsZEU3cK8U-LZUDf7Q"
  censusApiKey: ""
