apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: cpl-features
  labels:
    {{- include "cpl-coverage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  feastProject: cpl_coverage
  feastProjectDir:
    git:
      url: {{ .Values.git.repoURL }}
      ref: {{ .Values.git.ref }}
      featureRepoPath: feast
  services:
    registry:
      local:
        server: {}
  authz:
    noAuth: true
