apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: cpl-features
  labels:
    {{- include "cpl-coverage.labels" . | nindent 4 }}
    feature-store-ui: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  feastProject: cpl_coverage
  feastProjectDir:
    git:
      url: {{ .Values.git.repoURL }}
      ref: {{ .Values.git.ref }}
      featureRepoPath: feast
  services:
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
          - secretRef:
              name: postgres-secret
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          restAPI: true
          envFrom:
            - secretRef:
                name: postgres-secret
    ui: {}
  authz:
    noAuth: true
