{{- if .Values.secrets.mapboxToken }}
apiVersion: v1
kind: Secret
metadata:
  name: mapbox-token
  labels:
    {{- include "cpl-coverage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  MAPBOX_TOKEN: {{ .Values.secrets.mapboxToken | quote }}
{{- end }}
