apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-files
  labels:
    {{- include "cpl-coverage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  01_cleaning_pipeline.ipynb: |-
    {{ .Files.Get "files/01_cleaning_pipeline.ipynb" | nindent 4 }}
  02_fetch_isochrones.ipynb: |-
    {{ .Files.Get "files/02_fetch_isochrones.ipynb" | nindent 4 }}
  03_compute_coverage.ipynb: |-
    {{ .Files.Get "files/03_compute_coverage.ipynb" | nindent 4 }}
  04_aggregate_scores.ipynb: |-
    {{ .Files.Get "files/04_aggregate_scores.ipynb" | nindent 4 }}

